[colors.primary]
background = "0x1e1e2e"
foreground = "0xc0caf5"

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 11.25

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[scrolling]
history = 10000
